CREATE TABLE users (
    ukey INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uname VARCHAR(30) NOT NULL,
    upass VARCHAR(30) NOT NULL
);

INSERT INTO users (uname, upass) VALUES
    ("predawn", "gpbwjuynw"),
    ("roseslug", "jepvmexqbkf"),
    ("espy", "oaagww"),
    ("stropping", "mfapyrlhzg"),
    ("daughter", "xkcihwsjsnkpn"),
    ("stellated", "lyitgxvia"),
    ("asceses", "gwgkzgjdwryhv"),
    ("overswing", "dvpznxkkwmmt"),
    ("exotica", "szxudrhlb"),
    ("garboard", "zetfrnk"),
    ("satang", "xoliwmpg"),
    ("plesiosaurs", "eqwmvmszqiug"),
    ("beldames", "ojyuswfuzq"),
    ("putout", "cpvxxh"),
    ("compends", "yrpqze"),
    ("arthritis", "kspbkcb"),
    ("messaging", "bpfgni"),
    ("fearsomely", "ijisijb"),
    ("nominative", "xlllytghb"),
    ("anesthetized", "uslflsocefsnd"),
    ("presumptions", "gpgkma"),
    ("academicians", "mvxhgl"),
    ("crenelling", "lokbqsbt"),
    ("courlans", "veyflkxitutny"),
    ("lyrately", "yvcdkltby"),
    ("replenish", "nqnuzcuua"),
    ("parsers", "tyvzxx"),
    ("shiest", "wivbouwm"),
    ("nonheroes", "duieunhhap"),
    ("looted", "gllicp"),
    ("hypoderma", "ltvweeqch"),
    ("newest", "smyyrpbj"),
    ("etherifies", "tafflc"),
    ("toils", "bqdpcmyk"),
    ("poohs", "pivkkpwes"),
    ("wamble", "gddsnbveimxgz"),
    ("phasic", "xfucjrvhg"),
    ("fitch", "ogpvfr"),
    ("navette", "iiltoqpfj"),
    ("mesocyclones", "kpdkcrupquac"),
    ("rigorous", "oybwgam"),
    ("aestheticizes", "zilxdoxcbahhg"),
    ("respoke", "ltibpq"),
    ("lusterware", "ellyfya"),
    ("folkmotes", "bvelmuhfyufev"),
    ("goddaughters", "swzsgeku"),
    ("antimonopoly", "abxqsihgu"),
    ("anaglyph", "fbmhwrkvz"),
    ("birdlike", "ladffwkd")
;
